[package]
name = "test-chain-utils"
version = "0.14.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-core = { path = "../../core" }
hash = { path = "../hash" }
