[package]
name = "ckb-test-chain-utils"
version = "0.16.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-core = { path = "../../core" }
ckb-hash = { path = "../hash" }
lazy_static = "1.3.0"
