[package]
name = "nervos-notify"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
fnv = "1.0"
nervos-util = { path = "../util" }
crossbeam-channel = "0.1"
nervos-core = { path = "../core" }
