[package]
name = "ckb-notify"
version = "0.14.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
fnv = "1.0"
ckb-core = { path = "../core" }
crossbeam-channel = "0.3"
stop-handler = { path = "../util/stop-handler" }
ckb-logger = { path = "../util/logger" }
