[package]
name = "ckb-pool"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
rand = "0.5.0"
ckb-core = { path = "../core" }
ckb-chain = { path = "../chain" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
ckb-util = { path = "../util" }
ckb-time = { path = "../util/time" }
log = "0.4"
fnv = "1.0.3"
ckb-notify = { path = "../notify" }
ckb-verification = { path = "../verification" }
crossbeam-channel = "0.2"

[dev-dependencies]
env_logger = "0.4"
ethash = { git = "https://github.com/NervosFoundation/ethash", tag = "v1.0.0" }
ckb-db = { path = "../db" }
