[package]
name = "nervos-pool"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
rand = "0.5.0"
nervos-core = { path = "../core" }
nervos-chain = { path = "../chain" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
nervos-util = { path = "../util" }
nervos-time = { path = "../util/time" }
log = "0.4"
nervos-notify = { path = "../notify" }
nervos-verification = { path = "../verification" }
crossbeam-channel = "0.1"

[dev-dependencies]
env_logger = "0.4"
ethash = { git = "https://github.com/NervosFoundation/ethash", tag = "v1.0.0" }
