[package]
name = "hash"
version = "0.14.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
blake2b-rs = "0.1.4"

[dev-dependencies]
faster-hex = "0.3"
