[package]
name = "merkle-root"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
bigint = { git = "https://github.com/nervosnetwork/bigint" }
hash = {path = "../hash"}
