[package]
name = "ckb-dao"
version = "0.101.7"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "This crate provides implementation to calculate dao field"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../types", version = "= 0.101.7" }
ckb-chain-spec = { path = "../../spec", version = "= 0.101.7" }
ckb-dao-utils = { path = "./utils", version = "= 0.101.7" }
ckb-traits = { path = "../../traits", version = "= 0.101.7" }

[dev-dependencies]
ckb-db = { path = "../../db", version = "= 0.101.7" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.101.7" }
ckb-store = { path = "../../store", version = "= 0.101.7" }
tempfile = "3.0"
