[package]
name = "ckb-dao"
version = "0.21.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../types" }
ckb-chain-spec = { path = "../../spec" }
ckb-resource = { path = "../../resource" }
ckb-store = { path = "../../store" }
ckb-dao-utils = { path = "./utils" }
ckb-error = { path = "../../error" }

[dev-dependencies]
ckb-db = { path = "../../db" }
