language: rust
sudo: true
branches:
  only:
    - master
    - develop
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo
    - target-cache

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: osx
      rust: 1.29.0
      install:
        - cargo fmt --version || rustup component add rustfmt-preview
        - cargo clippy --version || rustup component add clippy-preview
      env: SUITE=ci
    - rust: 1.29.0
      addons:
        apt:
          packages:
            - git
            - autoconf
            - flex
            - bison
            - texinfo
            - libtool
      env: SUITE=ci-quick

script:
- make info
- make "$SUITE"

before_install:
- make cache-warm

before_cache:
- make cache-clean
