language: rust
sudo: true
cache:
  cargo: true
  timeout: 1024

git:
  depth: 2
  submodules: false

if: 'branch IN (master, develop) OR branch =~ /^rc\// OR type != push OR fork = true OR tag IS present'

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - rust: 1.33.0
      os: osx
      env: FMT=true CHECK=true TEST=true
    - rust: 1.33.0
      os: linux
      env: TEST=true

addons:
  apt:
    packages:
      - git
      - autoconf
      - flex
      - bison
      - texinfo
      - libtool

before_install: if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 8192; fi
install: ./devtools/ci/install.sh
script: ./devtools/ci/script.sh

before_cache:
- rm -rf ./target/debug/incremental/
- cargo sweep -f
