language: rust
sudo: true
branches:
  only:
    - master
    - develop
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo
    - target-cache

env:
  global:
    - CLIPPY_VERSION=0.0.204
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: osx
      rust: nightly-2018-05-23
      install:
        - cargo fmt --version || rustup component add rustfmt-preview --toolchain=nightly-2018-05-23
        - cargo clippy --version || cargo install clippy --vers $CLIPPY_VERSION --force
      env: SUITE=ci
    - rust: nightly-2018-05-23
      addons:
        apt:
          packages:
            - git
            - autoconf
            - flex
            - bison
            - texinfo
            - libtool
      env: SUITE=ci-quick

script:
- make info
- make "$SUITE"

before_install:
- make cache-warm

before_cache:
- make cache-clean
