language: rust
sudo: true
cache:
  timeout: 1024
  directories:
     - $HOME/.cargo/

env:
  global:
    - CLIPPY_VERSION=0.0.204

matrix:
  include:
    - os: osx
      rust: nightly-2018-05-23
      before_script:
        - rustup component add rustfmt-preview --toolchain=nightly-2018-05-23
        - bash -c 'if [[ ! -e $HOME/.cargo/bin/cargo-clippy ]]; then
            cargo install clippy --vers $CLIPPY_VERSION --force;
          fi'
    - rust: nightly-2018-05-23
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y git autoconf flex bison texinfo libtool
      before_script:
        - rustup component add rustfmt-preview --toolchain=nightly-2018-05-23
        - bash -c 'if [[ ! -e $HOME/.cargo/bin/cargo-clippy ]]; then
            cargo install clippy --vers $CLIPPY_VERSION --force;
          fi'

script:
- make ci
