language: rust
sudo: true
cache: cargo
matrix:
  include:
    - os: osx
      rust: nightly-2018-01-23
      before_script:
        - rustup component add rustfmt-preview --toolchain=nightly-2018-01-23
    - rust: nightly-2018-01-23
      before_script:
        - rustup component add rustfmt-preview --toolchain=nightly-2018-01-23


script:
- make ci
