language: rust
sudo: true
branches:
  except:
    - /.*-skip-ci$/
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

env:
  global:
    - CLIPPY_VERSION=0.0.204

matrix:
  include:
    - os: osx
      rust: nightly-2018-05-23
      install:
        - cargo fmt --version || rustup component add rustfmt-preview --toolchain=nightly-2018-05-23
        - cargo clippy --version || cargo install clippy --vers $CLIPPY_VERSION --force
    - rust: nightly-2018-05-23
      addons:
        apt:
          packages:
            - git
            - autoconf
            - flex
            - bison
            - texinfo
            - libtool
      install:
        - cargo fmt --version || rustup component add rustfmt-preview --toolchain=nightly-2018-05-23
        - cargo clippy --version || cargo install clippy --vers $CLIPPY_VERSION --force

script:
- make info
- make ci
