[package]
name = "nervos"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
nervos-util = { path = "util" }
nervos-core = { path = "core" }
nervos-chain = { path = "chain" }
nervos-miner = { path = "miner" }
nervos-db = { path = "db" }
nervos-network = { path = "network"}
nervos-pool = { path = "pool"}
nervos-rpc = { path = "rpc"}
nervos-time = { path = "util/time"}
logger = { path = "util/logger" }
bigint = { path = "util/bigint" }
dir = { path = "util/dir" }
crypto = { path = "util/crypto", features = ["rsa", "secp"] }
ctrlc = { version = "3.1", features = ["termination"] }
tera = "0.11"
lazy_static = "1.0"
bls = { git = "https://github.com/NervosFoundation/bls-rs.git" }
nervos-sync = { path = "sync"}

# The [patch] sections in Cargo.toml are only recognized in the root crate's manifest
[patch.crates-io]
# TODO: Update ring and solve conflicts
"ring" = { git = "https://github.com/briansmith/ring", rev = "3a14ef619559f7d4b69e2286d49c833409eef34a" }
# Using a version of rust-multihash that compiles on emscripten
# TODO: remove once merged upstream
"openssl-sys" = { git = "https://github.com/NervosFoundation/rust-openssl.git", branch = "pkcs8_der" }


[workspace]
members = [
    "util/logger",
    "util/hash",
    "util/merkle-root",
    "util/crypto",
    "util/dir",
    "network",
    "network/protocol",
    "sync",
    "core",
    "chain",
    "miner",
    "db",
    "pool",
    "rpc",
]
