[package]
name = "nervos"
version = "0.1.0"
authors = ["Nervos <dev@nervos.org>"]

[dependencies]
clap = "2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
nervos-util = { path = "./util" }
core = { path = "./core" }


[workspace]
members = [
	"util",
    # "network",
]
