[package]
name = "ckb"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
ckb-util = { path = "util" }
ckb-core = { path = "core" }
ckb-chain = { path = "chain" }
ckb-notify = { path = "notify"}
ckb-miner = { path = "miner" }
ckb-db = { path = "db" }
ckb-network = { path = "network"}
ckb-pool = { path = "pool"}
ckb-rpc = { path = "rpc"}
ckb-time = { path = "util/time"}
ckb-script= { path = "script"}
logger = { path = "util/logger" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
dir = { path = "util/dir" }
ctrlc = { version = "3.1", features = ["termination"] }
lazy_static = "1.0"
ckb-sync = { path = "sync"}
serde_yaml = "0.7"
config = "0.9"
reqwest = { git = "https://github.com/seanmonstar/reqwest" }
serde_json = "1.0"
crypto = {path = "util/crypto"}

[features]
default = ["pow_engine_cuckoo"]
pow_engine_cuckoo = []
pow_engine_ethash = []

[dev-dependencies]
tempdir = "0.3"

[workspace]
members = [
    "util/avl",
    "util/logger",
    "util/hash",
    "util/merkle-root",
    "util/crypto",
    "util/dir",
    "network",
    "network/protocol",
    "sync",
    "core",
    "chain",
    "miner",
    "db",
    "pool",
    "rpc",
    "notify",
    "verification",
    "script",
]
