[package]
name = "nervos"
version = "0.1.0"
authors = ["Nervos <dev@nervos.org>"]

[dependencies]
clap = "2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
nervos-util = { path = "./util" }
core = { path = "./core" }

# The [patch] sections in Cargo.toml are only recognized in the root crate's manifest
[patch.crates-io]
# TODO: Update ring and solve conflicts
"ring" = { git = "https://github.com/briansmith/ring", rev = "3a14ef619559f7d4b69e2286d49c833409eef34a" }
# Using a local improved version of multiaddr for now
# TODO: remove once merged upstream
"multiaddr" = { git = "https://github.com/libp2p/rust-libp2p" }
# Using a version of rust-multihash that compiles on emscripten
# TODO: remove once merged upstream
"multihash" = { git = "https://github.com/tomaka/rust-multihash", branch = "emscripten-hack" }

[workspace]
members = [
	"util",
    "network",
]
