[package]
name = "nervos"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
nervos-util = { path = "util" }
nervos-core = { path = "core" }
nervos-chain = { path = "chain" }
nervos-notify = { path = "notify"}
nervos-miner = { path = "miner" }
nervos-db = { path = "db" }
nervos-network = { path = "network"}
nervos-pool = { path = "pool"}
nervos-rpc = { path = "rpc"}
nervos-time = { path = "util/time"}
nervos-script= { path = "script"}
ethash = { git = "https://github.com/NervosFoundation/ethash", tag = "v1.0.0" }
logger = { path = "util/logger" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
dir = { path = "util/dir" }
ctrlc = { version = "3.1", features = ["termination"] }
tera = "0.11"
lazy_static = "1.0"
nervos-sync = { path = "sync"}
serde_yaml = "0.7"
config = "0.9"
nervos-verification = { path = "verification" }

[dev-dependencies]
tempdir = "0.3"

[workspace]
members = [
    "util/avl",
    "util/logger",
    "util/hash",
    "util/merkle-root",
    "util/crypto",
    "util/dir",
    "network",
    "network/protocol",
    "sync",
    "core",
    "chain",
    "miner",
    "db",
    "pool",
    "rpc",
    "notify",
    "verification",
    "script",
]
