[package]
name = "ckb"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
ckb-util = { path = "util" }
ckb-core = { path = "core" }
ckb-chain = { path = "chain" }
ckb-chain-spec = {path = "spec"}
ckb-notify = { path = "notify"}
ckb-miner = { path = "miner" }
ckb-db = { path = "db" }
ckb-network = { path = "network"}
ckb-pool = { path = "pool"}
ckb-rpc = { path = "rpc"}
ckb-time = { path = "util/time"}
ckb-script= { path = "script"}
logger = { path = "util/logger" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
dir = { path = "util/dir" }
ctrlc = { version = "3.1", features = ["termination"] }
lazy_static = "1.0"
ckb-sync = { path = "sync"}
config = "0.9"
serde_json = "1.0"
crypto = { path = "util/crypto"}
ckb-instrument = { path = "util/instrument", features = ["progress_bar"] }

[features]
default = ["pow_engine_cuckoo"]
pow_engine_cuckoo = []
pow_engine_ethash = []
integration_test = ["ckb-rpc/integration_test"]

[dev-dependencies]
tempfile = "3.0"

[workspace]
members = [
    "util/avl",
    "util/logger",
    "util/hash",
    "util/merkle-root",
    "util/crypto",
    "util/dir",
    "util/instrument",
    "network",
    "network/protocol",
    "sync",
    "core",
    "chain",
    "miner",
    "db",
    "pool",
    "rpc",
    "notify",
    "spec",
    "verification",
    "script",
    "benches"
]
