[package]
name = "ckb-verification"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
ethash = { git = "https://github.com/NervosFoundation/ethash", tag = "v1.0.0" }
log = "0.4"
ckb-core = { path = "../core" }
ckb-time = { path = "../util/time" }
ckb-chain = { path = "../chain" }
ckb-util = { path = "../util" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
merkle-root = {path = "../util/merkle-root"}
rayon = "1.0"

[dev-dependencies]
ckb-db = { path = "../db" }
ckb-notify = { path = "../notify" }
