[package]
name = "ckb-metrics-config"
version = "0.100.0-rc5"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2018"
description = "CKB metrics configurations."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
