[package]
name = "ckb-rpc"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
bigint = { git = "https://github.com/NervosFoundation/bigint" }
ckb-core = { path = "../core" }
ckb-network = { path = "../network" }
ckb-chain = { path = "../chain" }
ckb-db = { path = "../db" }
ckb-sync = { path = "../sync" }
ckb-pool = { path = "../pool" }
ckb-miner = { path = "../miner" }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-minihttp-server = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-server-utils = { git = "https://github.com/paritytech/jsonrpc" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"

ckb-protocol = { path = "../network/protocol" }
protobuf = "2.0.4"
