[package]
name = "nervos-rpc"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
bigint = { path = "../util/bigint" }
nervos-core = { path = "../core" }
nervos-network = { path = "../network" }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-minihttp-server = { git = "https://github.com/paritytech/jsonrpc" }

serde_json = "1.0"
log = "0.4"
