[package]
name = "ckb-wallet"
version = "0.13.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-core = { path = "../core" }
ckb-db = { path = "../db" }
ckb-notify = { path = "../notify" }
ckb-shared = { path = "../shared" }
ckb-store = { path = "../store" }
ckb-traits = { path = "../traits" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
bincode = "1.1"
serde = "1.0"
serde_derive = "1.0"
crossbeam-channel = "0.3"
log = "0.4"

[dev-dependencies]
tempfile = "3.0"
ckb-chain-spec = { path = "../spec" }
