[package]
name = "ckb-script-data-loader"
version = "0.15.3"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
numext-fixed-hash = { version = "0.1" }
ckb-core = { path = "../../core" }

