[package]
name = "ckb-store"
version = "0.14.2"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
bincode = "1.1"
serde = "1.0"
serde_derive = "1.0"
ckb-core = { path = "../core" }
ckb-db = { path = "../db" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
ckb-chain-spec = { path = "../spec" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }

[dev-dependencies]
tempfile = "3.0"
