jobs:
  - job: UnitTest
    condition: eq(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.34.2-x86_64-pc-windows-msvc'
      - script: make test
        displayName: Run unit tests
  - job: IntegrationTest
    condition: ne(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.34.2-x86_64-pc-windows-msvc'
      - script: make integration-windows
        displayName: Run integration tests
