version: 2
jobs:
  build:
    docker:
      - image: nervos/nervos-build:latest
    working_directory: ~/nervos-build
    steps:
      - checkout
      - run:
          name: format
          command: 'cargo fmt --all  -- --write-mode diff'
      - run: 
          name: build
          command: 'cargo build'
      - save_cache:
          key: nervos-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nervos-build
      - save_cache:
          key: deps-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo


  basic_test:
    docker:
      - image: nervos/nervos-build:latest
    working_directory: ~/nervos-build
    steps:
      - restore_cache:
          key: nervos-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: deps-{{ checksum "Cargo.lock" }}
      - run:
          name: test
          command: 'cargo test --all'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - basic_test:
          requires:
            - build
