[package]
name = "ckb-gen-types"
version = "0.112.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "Provides the generated types for CKB."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dev-dependencies]
ckb-hash = {path = "../hash", version = "= 0.112.0-pre"}

[features]
default = ["calc-hash", "check-data", "serialized-size", "std"]
calc-hash = ["blake2b-ref"]
check-data = []
capacity = []
serialized-size = []
std = ["molecule/std", "ckb-fixed-hash", "numext-fixed-uint"]

[dependencies]
molecule = { version = "0.7.5", default-features = false }
ckb-fixed-hash = { path = "../fixed-hash", version = "= 0.112.0-pre", optional = true}
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"], optional = true}
cfg-if = "1.0"
blake2b-ref = { version = "0.3.1", default-features = false, optional = true }
