[package]
name = "ckb-gen-types"
version = "0.112.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "Provides the generated types for CKB."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[features]
default = ["std"]
calc-hash = ["blake2b-ref"]
std = ["molecule/std"]

[dependencies]
molecule = { version = "0.7.5", default-features = false }
cfg-if = "1.0"
blake2b-ref = { version = "0.3.1", default-features = false, optional = true }