name: ckb
version: "0.1.0"
author: Nervos Core Dev <dev@nervos.org>
about: Nervos CKB - The Common Knowledge Base

subcommands:
    - run:
        about: Running ckb node
        args:
            - config:
                short: c
                long: config
                value_name: CONFIG
                help: Specify the configuration file PATH.
                takes_value: true
            - data-dir:
                short: d
                long: data-dir
                value_name: PATH
                help: Specify data directory.
                takes_value: true
            - chain:
                long: chain
                value_name: CHAIN
                help: Specify the chain spec file.
                takes_value: true
    - export:
        about: Export ckb data
        args:
            - data-dir:
                short: d
                long: data-dir
                value_name: PATH
                help: Specify data directory.
                takes_value: true
            - format:
                short: f
                long: format
                value_name: FORMAT
                help: Specify the format.
                required: true
                takes_value: true
            - chain:
                long: chain
                value_name: CHAIN
                help: Specify the chain spec file.
                takes_value: true
            - target:
                short: t
                long: target
                value_name: TARGET
                help: Specify the export target path.
                required: true
                index: 1

    - import:
        about: Import ckb data
        args:
            - data-dir:
                short: d
                long: data-dir
                value_name: PATH
                help: Specify data directory.
                takes_value: true
            - format:
                short: f
                long: format
                value_name: FORMAT
                help: Specify the format.
                required: true
                takes_value: true
            - chain:
                long: chain
                value_name: CHAIN
                help: Specify the chain spec file.
                takes_value: true
            - source:
                value_name: SOURCE
                required: true
    - cli:
        about: Running ckb cli
        subcommands:
            - rpc:
                about: Remote procedure call
                args:
                    - uri:
                        short: u
                        long: uri
                        help: Specify the rpc uri, e.g. http://localhost:3000
                        takes_value: true
                    - method:
                        short: m
                        long: method
                        help: Specify the rpc method, e.g. get_block_hash
                        takes_value: true
                    - params:
                        short: p
                        long: params
                        help: Specify the rpc params, e.g. [42]
                        takes_value: true
            - sign:
                about: Sign transaction
                args:
                    - private-key:
                        short: p
                        long: private-key
                        value_name: H256
                        help: Specify the private key
                        takes_value: true
                        required: true
                    - unsigned-transaction:
                        short: u
                        long: unsigned-transaction
                        value_name: TX JSON STRING
                        help: Specify the unsigned transaction json string
                        takes_value: true
                        required: true
            - keygen:
                about: Generate new key
