name: nervos
version: "0.1.0"
author: Nervos Core Dev <dev@nervos.org>
about: Nervos CKB - The Common Knowledge Base
args:
    - config:
        short: c
        long: config
        value_name: CONFIG
        help: Specify the configuration file.
        takes_value: true
subcommands:
    - run:
        version: "0.1.0"
        about: run
    - signer:
        version: "0.1.0"
        subcommands:
            - new:
                about: generate new signer
