[package]
name = "avl-merkle"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
bigint = { git = "https://github.com/nervosnetwork/bigint" }
ckb-db = { path = "../../db" }
hash = {path = "../hash"}
ckb-core = { path = "../../core" }
