[package]
name = "ckb-protocol"
version = "0.8.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
flatbuffers = { git = "https://github.com/google/flatbuffers", rev = "4f10da8d99c1a7bc8c9c7d06d2092a689f171d29" }
flatbuffers-verifier = { git = "https://github.com/nervosnetwork/cfb" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
byteorder = "1.3.1"
ckb-core = { path = "../core" }
hash = { path = "../util/hash"}
siphasher = "0.3.0"
rand = "0.6"
ckb-util = { path = "../util" }
ckb-merkle-tree = { path = "../util/merkle-tree"}
failure = "0.1.5"
