[package]
name = "ckb-network"
version = "0.21.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
ckb-util = { path = "../util" }
ckb-stop-handler = { path = "../util/stop-handler" }
ckb-logger = { path = "../util/logger" }
bytes = "0.4.12"
tokio = "0.1.18"
tokio-threadpool = "0.1"
futures = "0.1"
crossbeam-channel = "0.3"
p2p = { version="0.2.4", package="tentacle", features = ["molc"] }
p2p-ping = { version="0.3.6", package="tentacle-ping", features = ["molc"] }
p2p-discovery = { version="0.2.6", package="tentacle-discovery", features = ["molc"] }
p2p-identify = { version="0.2.7", package="tentacle-identify", features = ["molc"] }
faketime = "0.2.0"
lazy_static = "1.3.0"
generic-channel = { version = "0.2.0", features = ["all"] }
bs58 = "0.2.0"
sentry = "0.16.0"
faster-hex = "0.4"
ckb-hash = {path = "../util/hash"}
secp256k1 = {version = "0.15.0", features = ["recovery"] }
resolve = "0.2.0"
ckb-build-info = {path = "../util/build-info"}
num_cpus = "1.10"
snap = "0.2"
ckb-types = { path = "../util/types" }
ipnetwork = "0.14"

[dev-dependencies]
criterion = "0.3"
tempfile = "3.0.7"

[[bench]]
name = "peer_store"
harness = false
path = "src/benches/peer_store.rs"
