[package]
name = "ckb-network"
version = "0.7.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[features]
db-trace = ["rusqlite/trace"]

[dependencies]
rand = "0.6"
fnv = "1.0"
serde = "1.0"
serde_derive = "1.0"
ckb-util = { path = "../util" }
unsigned-varint = {git = "https://github.com/paritytech/unsigned-varint", features = ["codec"]}
log = "0.4.5"
bytes = "0.4.12"
tokio = "0.1.17"
futures = { version = "0.1.19", features = ["use_std"] }
snap = "0.2"
p2p = { version = "0.2.0-alpha.1", package="tentacle" }
secio = { version = "0.1.0", package="tentacle-secio" }
p2p-ping = { version = "0.2.0", package="tentacle-ping" }
p2p-discovery = { version = "0.1.0", package="tentacle-discovery" }
faketime = "0.2.0"
rusqlite = {version = "0.16.0", features = ["bundled"]}
lazy_static = "1.3.0"
r2d2 = "0.8.3"
r2d2_sqlite = "0.8.0"
generic-channel = { version = "0.2.0", features = ["all"] }

[dev-dependencies]
criterion = "0.2"
tempfile = "3.0.7"

[[bench]]
name = "sqlite_peer_store"
harness = false
path = "src/benches/sqlite_peer_store.rs"
