[package]
name = "nervos-core"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
bigint = { git = "https://github.com/NervosFoundation/bigint" }
hash = {path = "../util/hash"}
crypto = {path = "../util/crypto"}
merkle-root = {path = "../util/merkle-root"}
nervos-time = { path = "../util/time" }
nervos-protocol = { path = "../network/protocol" }
bit-vec = "0.5.0"