[package]
name = "ckb-core"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
bigint = { git = "https://github.com/nervosnetwork/bigint" }
byteorder = "1"
hash = {path = "../util/hash"}
crypto = {path = "../util/crypto"}
ckb-time = { path = "../util/time" }
bit-vec = "0.5.0"
ckb-util = { path = "../util" }
fnv = "1.0.3"
merkle-root = {path = "../util/merkle-root"}
