[package]
name = "core"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
bigint = { path = "../util/bigint" }
bls = {path = "../util/bls"}
hash = {path = "../util/hash"}
