[package]
name = "ckb-jsonrpc-types"
version = "0.44.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB common types for JSON serialization."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-constant = { path = "../constant", version = "= 0.44.0-pre" }
ckb-types = { path = "../types", version = "= 0.44.0-pre" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
faster-hex = "0.6"

[features]
test-only = ["ckb-constant/test-only", "ckb-types/test-only"]

[dev-dependencies]
proptest = "0.9"
regex = "1.1"
lazy_static = "1.3"
