[package]
name = "ckb-occupied-capacity-core"
version = "0.31.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
