[package]
name = "nervos-miner"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
log = "0.4"
bigint = { path = "../util/bigint" }
nervos-util = { path = "../util" }
nervos-time = { path = "../util/time" }
nervos-core = { path = "../core" }
nervos-pool = { path = "../pool" }
nervos-chain = { path = "../chain" }
nervos-db = { path = "../db" }
nervos-protocol = { path = "../network/protocol" }
nervos-network = { path = "../network" }
protobuf = "1.5"
