[package]
name = "occupied-capacity-macros"
version = "0.15.5"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.15"
proc-macro-hack = "0.5"
occupied-capacity-core = { path = "../core" }
