[package]
name = "ckb-async-runtime"
version = "0.39.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @doitian crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
ckb-stop-handler = { path = "../stop-handler", version = "= 0.39.0-pre" }
ckb-logger = { path = "../logger", version = "= 0.39.0-pre" }
ckb-spawn = {  path = "../spawn", version = "= 0.39.0-pre" }
