[package]
name = "ckb-resource"
version = "0.16.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
phf = "0.7.21"
includedir = "0.5.0"
tempfile = "3.0"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
serde = "1.0"
serde_derive = "1.0"
ckb-system-scripts = "0.1.0"

[build-dependencies]
includedir_codegen = "0.5.0"
walkdir = "2.1.4"
ckb-system-scripts = "0.1.0"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
