[package]
name = "ckb-resource"
version = "0.14.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
include = ["/specs", "/ckb.toml", "/ckb-miner.toml"]

[dependencies]
phf = "0.7.21"
includedir = "0.5.0"
tempfile = "3.0"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }

[build-dependencies]
includedir_codegen = "0.5.0"
walkdir = "2.1.4"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
hash = { path = "../util/hash"}
