[package]
name = "ckb-resource"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
phf = "0.7.21"
includedir = "0.5.0"
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
ckb-types = { path = "../util/types" }
# TODO: change this to stable published crate version once the system script PR
# is merged and published
ckb-system-scripts = { version = "0.2.0-alpha.3" }

[build-dependencies]
includedir_codegen = "0.5.0"
walkdir = "2.1.4"
ckb-types = { path = "../util/types" }
ckb-system-scripts = { version = "0.2.0-alpha.3" }
