[package]
name = "ckb-fixed-hash-macros"
version = "0.37.0"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[lib]
proc-macro = true

[dependencies]
ckb-fixed-hash-core = { path = "../core", version = "= 0.37.0" }
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"
