[ckb]
chain = "dev"

[logger]
file = "ckb.log"
filter = "info"
color = true

[network]
listen_address = "0.0.0.0:0"
boot_nodes = [
    "/ip4/127.0.0.1/tcp/12345/p2p/QmVMJYDCL2vDnk4PmRGNdDRTWRnfeboUsriYA9CixJsBRf"
]
reserved_nodes = [
    "/ip4/127.0.0.1/tcp/12345/p2p/QmVMJYDCL2vDnk4PmRGNdDRTWRnfeboUsriYA9CixJsBRf"
]
only_reserved_peers = false
min_peers = 4
max_peers = 8
secret_file = "secret"
nodes_file = "nodes.json"

[rpc]
listen_addr = "0.0.0.0:0"


[sync]
verification_level = "Full"
orphan_block_limit = 1024

[miner]
max_tx              = 1024
redeem_script_hash  = "0x6463e95f5f1f15415962563b0d4227635d8ae2a74137afbe3e052ef1f9470074"
