[ckb]
chain = "dev"

[logger]
filter = "info,sub-libp2p=debug,libp2p=debug,libp2p_kad=info,chain=warn,sync=debug,rpc=debug"

[rpc]
listen_addr = "0.0.0.0:3030"

[network]
boot_nodes = [
    "/ip4/47.75.42.29/tcp/12345/p2p/QmU6tySavbTF2uftZz1As2at4mxCr3QhhsFpfGpEbhBDiz"
]
reserved_nodes = []

[miner]
type_hash  = "0x321c1ca2887fb8eddaaa7e917399f71e63e03a1c83ff75ed12099a01115ea2ff"
