[logger]
filter = "info,sub-libp2p=debug,libp2p=debug,libp2p_kad=info,chain=warn,sync=debug"

[chain]
verification_level = "NoVerification"

[network]
boot_nodes = [
    "/ip4/47.75.42.29/tcp/12345/p2p/QmU6tySavbTF2uftZz1As2at4mxCr3QhhsFpfGpEbhBDiz"
]
reserved_nodes = []
