[package]
name = "ckb-snapshot"
version = "0.101.5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The ckb rocksdb snapshot wrapper"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.101.5" }
ckb-chain-spec = { path = "../../spec", version = "= 0.101.5" }
ckb-store = { path = "../../store", version = "= 0.101.5" }
ckb-db = { path = "../../db", version = "= 0.101.5" }
ckb-traits = { path = "../../traits", version = "= 0.101.5" }
ckb-proposal-table = { path = "../proposal-table", version = "= 0.101.5" }
arc-swap = "1.3"
ckb-db-schema = { path = "../../db-schema", version = "= 0.101.5" }
ckb-freezer = { path = "../../freezer", version = "= 0.101.5" }
