[package]
name = "ckb-chain-spec"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde_yaml = "0.7"
bigint = { git = "https://github.com/nervosnetwork/bigint" }
ckb-core = { path = "../core" }
ckb-chain = { path = "../chain" }
serde_derive = "1.0"
serde = "1.0"
ckb-pow = { path = "../pow" }
