[package]
name = "ckb-dao-utils"
version = "0.18.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
ckb-core = { path = "../../../core" }
failure = "0.1.5"
