[package]
name = "dao-utils"
version = "0.15.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-core = { path = "../../../core" }
ckb-script-data-loader = { path = "../../../script/data-loader" }
dao = { path = ".." }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
