[package]
name = "ckb-dao-utils"
version = "0.38.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../../types", version = "= 0.38.0-pre" }
ckb-error = { path = "../../../error", version = "= 0.38.0-pre" }
failure = "0.1.5"
derive_more = { version = "0.99.0", default-features = false, features = ["display"] }
