[package]
name = "ckb-launcher"
version = "0.43.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB tool to import/export chain data."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.43.2" }
ckb-store = { path = "../../store", version = "= 0.43.2" }
ckb-db = { path = "../../db", version = "= 0.43.2" }
ckb-migration-template = { path = "migration-template", version = "= 0.43.2" }
ckb-app-config = { path = "../app-config", version = "= 0.43.2" }
ckb-db-migration = { path = "../../db-migration", version = "= 0.43.2" }
ckb-logger = { path = "../logger", version = "= 0.43.2" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.43.2" }
ckb-error = { path = "../../error", version = "= 0.43.2" }
ckb-build-info = { path = "../build-info", version = "= 0.43.2" }
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.43.2" }
ckb-chain = { path = "../../chain", version = "= 0.43.2" }
ckb-shared = { path = "../../shared", version = "= 0.43.2" }
ckb-network = { path = "../../network", version = "= 0.43.2"}
ckb-rpc = { path = "../../rpc", version = "= 0.43.2"}
ckb-resource = { path = "../../resource", version = "= 0.43.2"}
ckb-network-alert = { path = "../network-alert", version = "= 0.43.2" }
ckb-sync = { path = "../../sync", version = "= 0.43.2"}
ckb-verification = { path = "../../verification", version = "= 0.43.2" }
ckb-verification-traits = { path = "../../verification/traits", version = "= 0.43.2" }
ckb-async-runtime = { path = "../runtime", version = "= 0.43.2" }
ckb-proposal-table = { path = "../proposal-table", version = "= 0.43.2" }
ckb-channel = { path = "../channel", version = "= 0.43.2" }
ckb-chain-spec = { path = "../../spec", version = "= 0.43.2" }
ckb-freezer = { path = "../../freezer", version = "= 0.43.2" }
ckb-notify = { path = "../../notify", version = "= 0.43.2" }
ckb-snapshot = { path = "../snapshot", version = "= 0.43.2" }
ckb-tx-pool = { path = "../../tx-pool", version = "= 0.43.2" }
ckb-stop-handler = { path = "../stop-handler", version = "= 0.43.2" }
p2p = { version="0.4.0-alpha.1", package="tentacle" }
num_cpus = "1.10"


[features]
with_sentry = [ "ckb-sync/with_sentry", "ckb-network/with_sentry", "ckb-app-config/with_sentry" ]
