[package]
name = "ckb-db"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
bincode = "1.0"
ckb-util = { path = "../util" }
ckb-core = { path = "../core" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
rocksdb = { git = "https://github.com/NervosFoundation/rust-rocksdb" }
fnv = "1.0.3"

[dev-dependencies]
tempfile = "3.0"
