[package]
name = "ckb-db"
version = "0.14.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-util = { path = "../util" }
rocksdb = { version = "0.12.2", default-features = false }
fnv = "1.0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.5"
log = "0.4"
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
semver = "0.9"

[dev-dependencies]
tempfile = "3.0"
