[package]
name = "ckb-db"
version = "0.27.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ckb-logger = { path = "../util/logger" }
tempfile = "3.0"
ckb-error = { path = "../error" }
libc = "0.2"

[dependencies.rocksdb]
git = "https://github.com/nervosnetwork/rust-rocksdb"
rev = "6cfc2cc"
