[package]
name = "nervos-db"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
bincode = "1.0"
nervos-util = { path = "../util" }
nervos-core = { path = "../core" }
bigint = { path = "../util/bigint" }
serde_derive = "1.0"
rocksdb = "0.10"
lru-cache = "0.1.1"

[dev-dependencies]
tempdir = "0.3"
