[package]
name = "ckb-script"
version = "0.8.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
byteorder = "1.3.1"
crypto = {path = "../util/crypto"}
ckb-core = { path = "../core" }
hash = {path = "../util/hash"}
ckb-vm = { git = "https://github.com/nervosnetwork/ckb-vm", rev = "d4638be" }
faster-hex = "0.3"
fnv = "1.0.3"
flatbuffers = { git = "https://github.com/google/flatbuffers", rev = "4f10da8d99c1a7bc8c9c7d06d2092a689f171d29" }
log = "0.4"
ckb-protocol = { path = "../protocol" }


[dev-dependencies]
proptest = "0.9"
