[package]
name = "ckb-script"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
crypto = {path = "../util/crypto"}
ckb-core = { path = "../core" }
serde = "1.0"
serde_derive = "1.0"
hash = {path = "../util/hash"}
ckb-vm = { path = "../vm" }
faster-hex = "0.1"
fnv = "1.0.3"
flatbuffers = "0.5.0"
ckb-protocol = { path = "../protocol" }


[dev-dependencies]
bigint = { git = "https://github.com/nervosnetwork/bigint" }
proptest = "0.8"
