[package]
name = "ckb-sync"
version = "0.8.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-chain = { path = "../chain" }
ckb-shared = { path = "../shared" }
ckb-core = { path = "../core" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
ckb-network = { path = "../network" }
log = "0.4"
fnv = "1.0"
ckb-protocol = { path = "../protocol" }
ckb-util = { path = "../util" }
faketime = "0.2.0"
bitflags = "1.0"
ckb-verification = { path = "../verification" }
serde = "1.0"
serde_derive = "1.0"
flatbuffers = { git = "https://github.com/google/flatbuffers", rev = "4f10da8d99c1a7bc8c9c7d06d2092a689f171d29" }
ckb-chain-spec = { path = "../spec" }
bloom-filters = "0.1.0"
ckb-traits = { path = "../traits" }
failure = "0.1.5"
bytes = "0.4.12"
hash = {path = "../util/hash"}

[dev-dependencies]
ckb-notify = { path = "../notify" }
ckb-db = { path = "../db" }
env_logger = "0.6"
crossbeam-channel = "0.3"
