[package]
name = "ckb-sync"
version = "0.100.0-rc5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The ckb sync/relayer protocols implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-chain = { path = "../chain", version = "= 0.100.0-rc5" }
ckb-shared = { path = "../shared", version = "= 0.100.0-rc5" }
ckb-store = { path = "../store", version = "= 0.100.0-rc5" }
ckb-db = { path = "../db", version = "= 0.100.0-rc5" }
ckb-app-config = {path = "../util/app-config", version = "= 0.100.0-rc5"}
ckb-types = {path = "../util/types", version = "= 0.100.0-rc5"}
ckb-network = { path = "../network", version = "= 0.100.0-rc5" }
ckb-logger = {path = "../util/logger", version = "= 0.100.0-rc5"}
ckb-metrics = {path = "../util/metrics", version = "= 0.100.0-rc5"}
ckb-util = { path = "../util", version = "= 0.100.0-rc5" }
ckb-verification = { path = "../verification", version = "= 0.100.0-rc5" }
ckb-verification-traits = { path = "../verification/traits", version = "= 0.100.0-rc5" }
ckb-chain-spec = { path = "../spec", version = "= 0.100.0-rc5" }
ckb-channel = { path = "../util/channel", version = "= 0.100.0-rc5" }
ckb-traits = { path = "../traits", version = "= 0.100.0-rc5" }
ckb-error = {path = "../error", version = "= 0.100.0-rc5"}
ckb-tx-pool = { path = "../tx-pool", version = "= 0.100.0-rc5" }
sentry = { version = "0.23.0", optional = true }
ckb-constant = { path = "../util/constant", version = "= 0.100.0-rc5" }
lru = "0.6.0"
futures = "0.3"
governor = "0.3.1"
tempfile = "3.0"
faketime = "0.2.0"
bitflags = "1.0"
dashmap = "4.0"
keyed_priority_queue = "0.3"

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.100.0-rc5" }
rand = "0.7"
ckb-dao = { path = "../util/dao", version = "= 0.100.0-rc5" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.100.0-rc5" }
ckb-chain = { path = "../chain", version = "= 0.100.0-rc5", features = ["mock"] }
ckb-launcher = { path = "../util/launcher", version = "= 0.100.0-rc5" }
faux = "^0.1"

[features]
default = []
stats = []
with_sentry = ["sentry"]
