[package]
name = "nervos-sync"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
protobuf = "2.0.2"
nervos-chain = { path = "../chain" }
nervos-core = { path = "../core" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
byteorder = "1.2.2"
hash = { path = "../util/hash"}
siphasher = "0.2.2"
rand = "0.5.0"
multiaddr = "0.3"
nervos-network = { path = "../network" }
log = "0.4"
fnv = "1.0"
nervos-protocol = { path = "../network/protocol" }
nervos-util = { path = "../util" }
nervos-pool = { path = "../pool" }
nervos-time = { path = "../util/time" }
nervos-notify = { path = "../notify" }
lazy_static = "1.0"
bitflags = "1.0"
nervos-verification = { path = "../verification" }
tokio = "0.1"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
rayon = "1.0.1"

[dev-dependencies]
nervos-db = { path = "../db" }
nervos-time = { path = "../util/time" }
env_logger = "0.5"
tempdir = "0.3"

