[package]
name = "ckb-sync"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
protobuf = "2.0.2"
ckb-chain = { path = "../chain" }
ckb-core = { path = "../core" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
byteorder = "1.2.2"
hash = { path = "../util/hash"}
siphasher = "0.2.2"
rand = "0.5.0"
multiaddr = "0.3"
ckb-network = { path = "../network" }
log = "0.4"
fnv = "1.0"
ckb-protocol = { path = "../network/protocol" }
ckb-util = { path = "../util" }
ckb-pool = { path = "../pool" }
ckb-time = { path = "../util/time" }
lazy_static = "1.0"
bitflags = "1.0"
ckb-verification = { path = "../verification" }
tokio = "0.1"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
rayon = "1.0.1"

[dev-dependencies]
ckb-notify = { path = "../notify" }
ckb-db = { path = "../db" }
ckb-time = { path = "../util/time" }
env_logger = "0.5"
tempdir = "0.3"
crossbeam-channel = "0.2"
merkle-root = {path = "../util/merkle-root"}
