[package]
name = "ckb-shared"
version = "0.30.1-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-types = { path = "../util/types" }
ckb-chain-spec = { path = "../spec" }
ckb-store = { path = "../store" }
ckb-db = { path = "../db" }
ckb-proposal-table = { path = "../util/proposal-table" }
arc-swap = "0.4"
ckb-error = { path = "../error" }
ckb-snapshot = { path = "../util/snapshot" }
ckb-tx-pool = { path = "../tx-pool" }
ckb-verification = { path = "../verification" }
ckb-notify = { path = "../notify" }
