[package]
name = "ckb-shared"
version = "0.21.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-types = { path = "../util/types" }
ckb-chain-spec = { path = "../spec" }
ckb-store = { path = "../store" }
ckb-db = { path = "../db" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
ckb-logger = { path = "../util/logger" }
ckb-traits = { path = "../traits" }
ckb-reward-calculator = { path = "../util/reward-calculator" }
ckb-proposal-table = { path = "../util/proposal-table" }
# DO NOT UPDATE "im", until clippy#4121 be solved
# https://github.com/rust-lang/rust-clippy/issues/4121
im = "~12.3"
arc-swap = "0.4"
ckb-error = { path = "../error" }
ckb-snapshot = { path = "../util/snapshot" }
ckb-tx-pool = { path = "../tx-pool" }

[dev-dependencies]
env_logger = "0.6"
tempfile = "3.0"
rand = "0.6"
serde_json = "1.0"
ckb-chain = { path = "../chain" }
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
