[package]
name = "bigint"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
uint = { path = "./uint", version = "0.1" }
fixed-hash = { path = "./fixed-hash", version = "0.1.1" }
crunchy = "0.1.5"
bigint-serialize = { version = "0.2", path = "./serialize", optional = true }
serde = { version = "1.0", optional = true }

[features]
default = ["std", "heapsizeof", "serialize"]
std = ["uint/std", "fixed-hash/std"]
heapsizeof = ["uint/heapsizeof", "fixed-hash/heapsizeof"]
serialize = ["std", "bigint-serialize", "serde"]
use_asm = ["uint/use_asm"]
