data_dir = "default"

[db]
path = "default/db"

[chain]
spec = "spec/dev.toml"

[logger]
file = "ckb.log"
filter = "info"
color = true

[network]
listen_addresses = ["/ip4/0.0.0.0/tcp/8115"]
bootnodes = []
reserved_nodes = []
only_reserved_peers = false
min_peers = 4
max_peers = 8
secret_file = "secret_key"
peer_store_path = "peer_store.db"

[rpc]
listen_address = "0.0.0.0:8114"

# Default is 10MiB = 10 * 1024 * 1024
max_request_body_size = 10485760

# List of API modules: ["Net", "Pool", "Miner", "Chain", "Trace"]
modules = ["Net", "Pool", "Miner", "Chain"]

[sync]
verification_level = "Full"
orphan_block_limit = 1024

[tx_pool]
max_pool_size = 10000
max_orphan_size = 10000
max_proposal_size = 10000
max_cache_size = 1000
max_pending_size = 10000
trace = 100
txs_verify_cache_size = 100000

[block_assembler]
# value is set as always_success script
reference = "0x28e83a1277d48add8e72fadaa9248559e1b632bab2bd60b27955ebc4c03800a5"
args = []
