[package]
name = "ckb-freezer"
version = "0.39.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.39.0-pre" }
ckb-error = { path = "../error", version = "= 0.39.0-pre" }
ckb-logger = { path = "../util/logger", version = "= 0.39.0-pre" }
ckb-shared = { path = "../shared", version = "= 0.39.0-pre" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.39.0-pre" }
crossbeam-channel = "0.3"
ckb-store = { path = "../store", version = "= 0.39.0-pre" }
fs2 = "0.4.3"

[dev-dependencies]
tempfile = "3.0"
