[package]
name = "ckb-instrument"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
ckb-core = { path = "../../core" }
ckb-chain = { path = "../../chain" }
ckb-db = { path = "../../db" }
ckb-chain-spec = {path = "../../spec"}
dir = { path = "../dir" }
serde_json = "1.0"
