[package]
name = "ckb-instrument"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
ckb-core = { path = "../../core" }
ckb-chain = { path = "../../chain" }
serde_json = "1.0"
indicatif = { version = "0.9.0", optional = true }

[features]
progress_bar = ["indicatif"]
