[package]
name = "ckb-chain"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
log = "0.4"
ckb-core = { path = "../core" }
ckb-util = { path = "../util" }
ckb-db = { path = "../db" }
avl-merkle = { path = "../util/avl" }
bigint = { git = "https://github.com/nervosnetwork/bigint" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache" }
fnv = "1.0.3"
ckb-time = { path = "../util/time" }
ckb-notify = { path = "../notify" }

[dev-dependencies]
env_logger = "0.4"
tempfile = "3.0"
rand = "0.5.0"
