[package]
name = "nervos-chain"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
log = "0.4"
rand = "0.5.0"
nervos-core = { path = "../core" }
nervos-util = { path = "../util" }
nervos-db = { path = "../db" }
avl-merkle = { path = "../util/avl" }
bigint = { git = "https://github.com/NervosFoundation/bigint" }
lru-cache = { git = "https://github.com/NervosFoundation/lru-cache" }
fnv = "1.0.3"
nervos-time = { path = "../util/time" }
ethash = { git = "https://github.com/NervosFoundation/ethash", tag = "v1.0.0" }
nervos-notify = { path = "../notify" }

[dev-dependencies]
env_logger = "0.4"
tempdir = "0.3"
