[package]
name = "nervos-chain"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
log = "0.4"
nervos-core = { path = "../core" }
bigint = { path = "../util/bigint" }
hash = { path = "../util/hash" }
kvdb = { path = "../util/kvdb" }

[dev-dependencies]
env_logger = "0.4"
