[package]
name = "crypto"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
secp256k1 = { git = "https://github.com/NervosFoundation/rust-secp256k1", optional = true, features = ["rand"] }
lazy_static = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
bigint = { path = "../bigint" }
rand = "0.4"
rustc-hex = "1.0"
crunchy = "0.1.5"

[features]
default = ["secp"]
secp = ["secp256k1"]
dev = []
