[package]
name = "crypto"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
secp256k1 = { git = "https://github.com/NervosFoundation/rust-secp256k1", optional = true, features = ["rand"] }
lazy_static = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
bigint = { git = "https://github.com/NervosFoundation/bigint" }
rand = "0.5.0"
rustc-hex = "1.0"
crunchy = "0.2"
openssl = { git = "https://github.com/NervosFoundation/rust-openssl.git", branch = "pkcs8_der", optional = true }
serde = "1.0"
serde_derive = "1.0"

[features]
default = ["secp"]
secp = ["secp256k1"]
bech32 = []
rsa = ["openssl"]
dev = ["secp", "bech32", "rsa"]
