[package]
name = "crypto"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[dependencies]
secp256k1 = { git = "https://github.com/nervosnetwork/rust-secp256k1", optional = true, features = ["rand"] }
lazy_static = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
rand = "0.6"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
faster-hex = "0.1"
crunchy = "0.2"

[features]
default = ["secp"]
secp = ["secp256k1"]
bech32 = []
dev = ["secp", "bech32"]
