[package]
name = "ckb-benches"
version = "0.22.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]


[dev-dependencies]
criterion = "0.3"
ckb-pow = { path = "../pow" }
ckb-chain = { path = "../chain" }
ckb-types = { path = "../util/types" }
ckb-shared = { path = "../shared" }
ckb-store = { path = "../store" }
ckb-chain-spec = { path = "../spec" }
ckb-db = { path = "../db" }
rand = "0.6"
tempfile = "3.0"
ckb-traits = { path = "../traits" }
ckb-hash = {path = "../util/hash"}
ckb-occupied-capacity = { path = "../util/occupied-capacity"}
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
ckb-dao-utils = { path = "../util/dao/utils" }
ckb-dao = { path = "../util/dao" }
ckb-system-scripts = { path = '/Users/quake/workspace/ckb-system-scripts' }
lazy_static = "1.3.0"
ckb-crypto = { path = "../util/crypto" }
faketime = "0.2.0"
ckb-miner = { path = "../miner" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-verification = { path = "../verification" }
ckb-tx-pool = { path = "../tx-pool" }

[[bench]]
name = "bench_main"
harness = false

[features]
default = []
ci = []
