[package]
name = "ckb-network-alert"
version = "0.111.0-rc8"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The alert protocol implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-multisig = { path = "../multisig", version = "= 0.111.0-rc8" }
ckb-types = { path = "../types", version = "= 0.111.0-rc8" }
ckb-util = { path = "..", version = "= 0.111.0-rc8" }
ckb-network = { path = "../../network", version = "= 0.111.0-rc8" }
ckb-notify = { path = "../../notify", version = "= 0.111.0-rc8"}
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.111.0-rc8" }
ckb-logger = { path = "../logger", version = "= 0.111.0-rc8"}
ckb-app-config = { path = "../app-config", version = "= 0.111.0-rc8" }
ckb-error = { path = "../../error", version = "= 0.111.0-rc8" }
ckb-systemtime = { path = "../systemtime", version = "= 0.111.0-rc8" }
lru = "0.7.1"
semver = "1.0"

[dev-dependencies]
ckb-crypto = { path = "../crypto", version = "= 0.111.0-rc8" }
ckb-async-runtime = { path = "../runtime", version = "= 0.111.0-rc8" }
once_cell = "1.8.0"
ckb-systemtime = {path = "../systemtime", version = "= 0.111.0-rc8", features = ["enable_faketime"]}
faster-hex = "0.6"
serde_json = "1.0"
