name: Dummy CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  always_success:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This job allows showing checks status without requiring any of them."
