name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: yangby-cryptape/cargo-audit-check-action@customized-for-ckb
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
