name: Smoking test suit

on:
  workflow_dispatch:
env:
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  TESTNET_DATA_SNAPSHOT: ${{secrets.TESTNET_DATA_SNAPSHOT}}
  CARGO_TARGET_DIR: ${{ github.workspace }}/../target

jobs:
   Start_and_sync:
    runs-on: [self-hosted,Linux]
    steps:
    - uses: actions/checkout@v2
    - name: Build CKB binary
      run: |
        make build
        cp ${CARGO_TARGET_DIR}/release/ckb ${{ github.workspace }}/ckb
    - name: Download&Unzip testnet data sanpshot
      run: |
        if [ ! -f "/tmp/testnet-data.tar.gz" ]; then
           curl -L https://nervos-data.oss-accelerate.aliyuncs.com/testnet-data.tar.gz -o /tmp/testnet-data.tar.gz
        fi
        tar -zxf /tmp/testnet-data.tar.gz -C /tmp
    - name: Update ExecStart&StandardOutput
      run: |
          sed -i  "s#ExecStart=.*#ExecStart=${{github.workspace}}/ckb run -C ${{github.workspace}}#g" ${{ github.workspace }}/devtools/somking_test/ckb.service
          sed -i  "s#StandardOutput=.*#StandardOutput=file:${{github.workspace}}/data/logs/run.log#g" ${{ github.workspace }}/devtools/somking_test/ckb.service
    - name: Init testnet
      run: ${{ github.workspace }}/ckb init -c testnet -C ${{ github.workspace }} --force
    - name: copy snapshot data to ckb
      run: |
        cp -r /tmp/data  ${{ github.workspace }}
    - name: Migration check
      run: |
        ${{ github.workspace }}/devtools/somking_test/check-migrate.sh
    - name: Start ckb service.
      if: ${{ success() }}
      run: |
            sudo cp ${{ github.workspace }}/devtools/somking_test/ckb.service /etc/systemd/system/ckb.service
            sudo systemctl daemon-reload
            sudo systemctl enable ckb
            sudo service ckb start
    - name: Ensure the ckb service is health.
      run: ${{ github.workspace }}/devtools/somking_test/tip_block_growth_check.sh
    - name: Stop & clean ckb service.
      if: ${{ always() }}
      run: |
         sudo service ckb stop
         sudo rm /etc/systemd/system/ckb.service
         rm -rf /tmp/data
    env:
      CKB_DIR: ${{ github.workspace }}