name: Sync Mainnet

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'pkg/*'

jobs:
  sync-mainnet:
    runs-on: [ self-hosted, linux ]
    if: ${{ github.repository_owner == 'nervosnetwork' }}
    timeout-minutes: 1200
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      GITHUB_BRANCH: ${{ github.ref_name }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: nervosnetwork/ckb-integration-test
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.61.0
      - run: rustup component add rustfmt
      - run: sudo apt update && sudo apt -y install ansible
      - run: sudo apt-get update && sudo apt-get install libssl-dev pkg-config libclang-dev -y && sudo apt-get install -y gcc-multilib
      - run: wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip && unzip terraform_1.1.2_linux_amd64.zip && sudo cp terraform /usr/bin/
      - run: sudo apt-get install -y wget ca-certificates && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' && sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib
      - name: Get Current Date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "START_TIME=$(date +%Y-%m-%d' '%H:%M:%S.%6N)" >> $GITHUB_ENV
          echo "CKB_COMMIT_ID=$(git describe --dirty --always --match _EXCLUDE__ --abbrev=7)" >> $GITHUB_ENV
          echo "CKB_COMMIT_TIME=$(git log -1 --date=iso "--pretty=format:%cd" | cut -d ' ' -f 1,2)" >> $GITHUB_ENV
      - name: Start
        timeout-minutes: 1200
        env:
          JOB_ID: "sync-mainnet-${{ github.repository_owner }}-${{ github.ref_name }}-${{ steps.date.outputs.date }}-in-10h"
        run: ./ckb-sync-mainnet/script/sync-mainnet.sh run
      - name: Set test state when sync-mainnet success.
        if: ${{ success() }}
        run: echo "GITHUB_RUN_STATE=0" >> $GITHUB_ENV
      - name: Set test state when sync-mainnet failed.
        if: ${{ failure() }}
        run: echo "GITHUB_RUN_STATE=1" >> $GITHUB_ENV
      - name: insert report to postgres
        if: ${{ always() }}
        env:
          JOB_ID: "sync-mainnet-${{ github.repository_owner }}-${{ github.ref_name }}-${{ steps.date.outputs.date }}-in-10h"
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ckbtest
        run: |
            [ -z "${PGHOST}" ] || ./ckb-sync-mainnet/script/sync-mainnet.sh insert_report_to_postgres
      - name: Clean Up
        if: ${{ always() }}
        env:
          JOB_ID: "sync-mainnet-${{ github.repository_owner }}-${{ github.ref_name }}-${{ steps.date.outputs.date }}-in-10h"
        run: ./ckb-sync-mainnet/script/sync-mainnet.sh clean
