name = "ckb_testnet"

[genesis]
version = 0
parent_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
timestamp = 0
difficulty = "0x1000"
uncles_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
hash = "0x298f349c8cdfadf46e8008e72afe6da78b1ea1b7d86470ea71bb0e404c5c9d7f"

[genesis.seal]
nonce = 0
proof = [0]

[params]
initial_block_reward = 50000
max_block_cycles = 100000000
cellbase_maturity = 10

[pow]
func = "Cuckoo"

[pow.params]
# the 2-log of the graph size, which is the size in bits of the node
# identifiers
edge_bits = 15

# length of the cycle to be found, must be an even number, a minimum of 12 is
# recommended
cycle_length = 12

# An array list paths to system cell files, which is absolute or relative to
# the directory containing this config file.
[[system_cells]]
path = "cells/secp256k1_blake2b_sighash_all"
